import type { Metadata } from "next";
import { Geist, Geist_Mono, Oxanium } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oxanium = Oxanium({
  variable: "--font-oxanium",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { RoleProvider } from "@/contexts/role-context"
import { ThemeProvider } from "@/components/theme-provider"
import { getSession } from "@/lib/auth"
import { Role } from "@prisma/client"

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getSession()
  // Default to ADMIN if no session (though middleware should catch this, except for login page)
  // Actually, if on login page, session is null.
  const userRole = session?.user?.role as Role || 'ADMIN'

  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${oxanium.variable} antialiased font-sans`}
      >
        <RoleProvider initialRole={userRole}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </RoleProvider>
      </body>
    </html>
  )
}
